### ISSUE TITLE
Agendar entrevista para alunos

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#437]
- Na página de inscrições, inserir um botão para agendamento de entrevista 
- Na página de agendamento de entrevista, cadastrar todos os horários disponíveis (Ex.: 05/05 AB Manhã)
- Na página de agendamento de entrevista, deverá conter uma lista com o nome de todos os alunos inscritos e aptos para a entrevista
- O agendamento ocorrerá baseado na alocação de cada aluno nos horários cadastrados, ou seja, cada horário terá uma lista de alunos a serem entrevistados
- O agendamento deve ser enviado por e-mail para os alunos

**Comment by allanfvc** [comment]
Colocar breadcrumb
