### ISSUE TITLE
Criar tabela editável na página Análise de Documentos

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#439]
A tabela em questão tem o propósito de comparar as informações cedidas pelo aluno com as informações que constam na documentação. Portanto:

- A tabela segue abaixo em imagem
- As informações cedidas pelo aluno não devem ser alteradas
- Deve haver uma linha abaixo da linha de respostas para que o avaliador possa colocar as informações reais, caso precise
- Para as informações que não vierem do formulário de inscrição, deixar o campo do aluno em branco

![Sem título.png](https://zube.io/files/npi-ufc-qxd/6f5205b8852e1786dc627e89c547ecc9.png)

**Comment by allanfvc** [comment]
1. Erros: 
 1. Erro no navegador: 
Exception evaluating SpringEL expression: "inscricao.analiseDocumentacao.parecer.nome" (selecao/visualizar-inscricoes:72)
 Log de erro na IDE: org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'nome' cannot be found on null
 1. Erro no navegador: Unknown name value [deferido] for enum class [br.ufc.npi.auxilio.enums.Resultado]; nested exception is java.lang.IllegalArgumentException: Unknown name value [deferido] for enum class [br.ufc.npi.auxilio.enums.Resultado]
 Log de erro na IDE: java.lang.IllegalArgumentException: Unknown name value [deferido] for enum class [br.ufc.npi.auxilio.enums.Resultado]
 1. Erro no navegador: Exception evaluating SpringEL expression: "inscricao.visitaDomiciliar.resultado.nome eq T(br.ufc.npi.auxilio.enums.Resultado).NAO_AVALIADO.nome" (selecao/visualizar-inscricoes:114)
 Log de erro na IDE: org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 27): Property or field 'resultado' cannot be found on object of type 'br.ufc.npi.auxilio.model.VisitaDomiciliar' - maybe not public?

1. Sugestões:

 1. Adicionar uma mascara de valores em reais após o preenchimento dos valor por parte do avaliador, nos campos de *rendas* e quando realizado o cálculo da renda per capta;
 1. Quando realizado o cálculo da renda per capta com os novos valores, utilizar apenas duas casas decimais após a vírgula.

**Comment by thalita-moura** [comment]
- Colocar a coluna Benefícios/Governo com texto livre.

- Atualizar a tabela geral com os valores modificados na tabela editável.

- Não devem ser atualizados os valores da página de detalhes de inscrição (valores fornecidos pelo Aluno)
