### ISSUE TITLE
Editar página Detalhes Aluno

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#440]
- O acesso a página se dará por meio do nome do aluno que se encontra em forma de link na tabela da página de inscrições.
- A página deve conter os seguintes itens de menu: Detalhes da Inscrição, Análise de Documentos, Entrevista e Visita Domiciliar.
- O item de menu Detalhes da Inscrição já tem sua página implementada. Precisa integrar as outras páginas ao restante dos itens de menu.

**Comment by allanfvc** [comment]
Exception evaluating SpringEL expression: "inscricao.resultado.nome" (base/base-menu-inscricao:41)
