### ISSUE TITLE
Adicionar botão adicionar arquivos

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#441]
- O aluno deve ter a opção de adicionar os arquivos ao final da página de inscrições.

- Essa funcionalidade é a mesma já implementada na página de seleções do aluno, conforme imagem abaixo:

![Sem título.png](https://zube.io/files/npi-ufc-qxd/0561404931ddd15c66912a59fdd30906.png)

**Comment by jvitorc17** [comment]
A opção de anexar arquivos deve estar também na página que verifica os dados. 
A opção de anexar deve ser retirada do formulário de cadastro.
