### ISSUE TITLE
Implementar roteiro de entrevista - Back end

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#443]
Histórias de usuário 04 e 05

**Comment by allanfvc** [comment]
Com a separação dos tipos de seleção, os campos referentes a Bolsa de Iniciação Acadêmica, pertencem apenas as seleções do tipo Bolsa de Iniciação Acadêmica, favor atualizar o formulário.

**Comment by thalita-moura** [comment]
Resolver conflitos.
