### ISSUE TITLE
Implementar Análise de Documentos - Back end

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#458]

**Comment by allanfvc** [comment]
1. Erros: 
 1. Erro no navegador: Exception evaluating SpringEL expression: "inscricao.analiseDocumentacao.resultado.nome eq 'não avaliado'" (selecao/visualizar-inscricoes:84)
  Log de erro na IDE: org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'nome' cannot be found on null
