### ISSUE TITLE
Melhorias na página de inscrição (View Aluno)

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#476]
- Trocar 'Naturalidade' por 'Local de Nascimento'

- No campo 'Tempo Gasto p/ deslocamento' mudar para texto livre

- No campo Parentesco da Situação socioeconômica, se a opção 'Outro' for escolhida, adicionar campo de texto para especificar esse outro  

- Na identificação do Aluno, deixar o campo 'Ano Ingresso' editável

**Comment by allanfvc** [comment]
Formulário abaixos estão desconfigurados:

![Captura de tela de 2017-06-19 13-47-42.png](https://zube.io/files/npi-ufc-qxd/9429228b055a31feac62991c6a414c23.png)
![Captura de tela de 2017-06-19 13-49-49.png](https://zube.io/files/npi-ufc-qxd/3b41a4e828d107fd2f3aedb9d0e0a524.png)

**Comment by thalita-moura** [comment]
Sugestões de melhorias:

- Colocar o valor da descrição do parentesco e não 'outro'
- Na descrição do tempo de deslocamento, colocar '* Tempo gasto com deslocamento (horas/minutos)"
- Adicionar botão voltar
