### ISSUE TITLE
Verificar erro ao adicionar um arquivo para upload de documentação

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#478]
- O sistema não está permitindo adicionar nome de arquivo já utilizado em outra seleção. Ex.: O sistema não permite que nome RG seja cadastrado na seleção 2, caso já tenha sido utilizado na seleção 1.

**Comment by ualisolima** [comment]
Para resolver esse problema basta retirar a restrição de chave única no banco de dados, na tabela tipo_documento.
