### ISSUE TITLE
Melhorias: Nenhuma mensagem é mostrada na análise de documentos e visita

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#494]
COORDENADOR

- Ao salvar/editar analise documentos nenhuma mensagem é mostrada.

- Ao salvar/editar visita domiciliar nenhuma mensagem é mostrada. 

- Para as três etapas: após finalizar, redirecionar para a própria página.

- Manter padrão dos botões para CANCELAR/FINALIZAR nas três etapas, como na imagem abaixo.

![Sem título.png](https://zube.io/files/npi-ufc-qxd/7d6bdba8fcc18fdd91c54dc3a4c1978f.png)

**Comment by allanfvc** [comment]
Em análise de documentos, ao salvar uma análise fora do prazo de inscrição aparece um erro. Verificar se erro foi corrigido na master mais recente.
