### ISSUE TITLE
BUG: Imagens e formulário na pag visita domiciliar

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#495]
COORDENADOR

- Na página de visita domiciliar a janela não limita a seleção para documentos apenas do tipo imagem, e ao selecionar um arquivo que não é imagem o sistema é direcionado para uma pagina de erro do springboot.

- Na página de visita domiciliar ao editar uma visita já realizada, não é possível apagar fotos adicionadas ou o formulário adicionado.

**Comment by allanfvc** [comment]
No campo imagens: arquivos estão sendo sobrepostos a medida que são adicionados, esse o comportamento esperado?

**Comment by JuniimSI** [comment]
No campo imagem e no campo formulário, dependendo do tamanho do nome, está passando do card. Solução: redimensionar o card de acordo com o tamanho do nome.extensao do arquivo.

**Comment by thalita-moura** [comment]
O comportamento esperado é que os arquivos possam ser excluídos e outros possam ser adicionados (sem sobrepor os arquivos existentes).
