### ISSUE TITLE
BUG: Data de entrevista aparece para todas seleções

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#507]
Ao cadastrar um horário para uma data já existente em outra seleção, o sistema carrega todos os horários na seleção corrente.

**Comment by allanfvc** [comment]
Não está sendo possível adicionar horários de entrevistas em determinados dias. Sem informação de erro.

**Comment by allanfvc** [comment]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jun 28 15:30:46 BRT 2017
There was an unexpected error (type=Internal Server Error, status=500).
Não é possível realizar inscrição fora do prazo

**Comment by thalita-moura** [comment]
Ocorre um erro ao tentar cadastrar um horário já cadastrado em outra seleção.

**Comment by thalita-moura** [comment]
Problema resolvido em #514_BUG_finalizar_tarefas_na_view_Aluno

**Comment by JuniimSI** [comment]
Qual erro apareceu?

**Comment by thalita-moura** [comment]
Não é possível cadastrar o horário, algo assim.

**Comment by thalita-moura** [comment]
Tratar campo null na data
