### ISSUE TITLE
Colocar parecer final como editável

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-assuntos-estudantis#531]
Possibilitar que o coordenador altere o parecer final. 
Por default, o resultado do parecer final será automaticamente calculado com base nos resultados parciais das etapas da seleção (isso já acontece hoje).

**Comment by allanfvc** [comment]
Teste: 
Falta campo de observações.
Aba do editar parecer final não está pré-selecionado.

**Comment by thalita-moura** [comment]
Erro Aluno Duplicado em duas listas:

-Se o aluno tiver selecionado e ao modificar o Parecer Final para Indeferido, ocorre o problema de ele cair em duas listas (deferido/selecionado e indeferido).

**Comment by thalita-moura** [comment]
Retirar aba. Abrir apenas uma janela temporária (modal).

**Comment by thalita-moura** [comment]
Corrigir tempo de mensagem.

**Comment by thalita-moura** [comment]
Verificar conflitos
